# Generated by Django 3.1 on 2021-03-01 04:47

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Launguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('launguage', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('date', models.DateField(auto_now_add=True)),
                ('url', models.CharField(blank=True, max_length=120, null=True)),
                ('content', ckeditor.fields.RichTextField(blank=True, max_length=12000, null=True)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Published', 'Published'), ('Private', 'Private')], max_length=120)),
                ('blog_type', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='blog.type')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
